version: "3.9"

services:
  backend: 
    build: ./
    environment:
      - APP__CONFIG=${APP_CONFIG}
      - APP__LDAP__HOST=ldap
      - APP__PG__HOST=postgres
      - APP__PG__PORT=5432
      - APP__PG__PASSWORD=postgres
    ports: ["8081:${APP__WEB__PORT}"]
    depends_on:
      - ldap
      - postgres
    command: ["python", "main.py"]
  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=${APP__LDAP__ORGANISATION}
      - LDAP_DOMAIN=${APP__LDAP__DOMAIN}
      - LDAP_ADMIN_PASSWORD=${APP__LDAP__PASSWORD}
    ports:
      - "${APP__LDAP__PORT}:389"     # LDAP
      - "636:636"     # LDAPS
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./ldap_config:/etc/ldap/slapd.d
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8083:80"
    depends_on:
      - ldap
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${APP__PG__BASE_DB}
    ports:
      - "${APP__PG__PORT}:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  my_postgres_data: